# Generated by Django 4.2.3 on 2023-07-23 11:49

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Mention",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("mention_text", models.CharField(max_length=200)),
                ("url", models.URLField()),
            ],
        ),
    ]
