# Generated by Django 4.2.3 on 2023-07-28 15:24

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("blobApp", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Blob",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("blob", models.CharField(max_length=100, unique=True)),
                ("date", models.DateField(default=django.utils.timezone.now)),
                ("time", models.TimeField(default=datetime.time(15, 24, 6, 676199))),
            ],
        ),
        migrations.RenameField(
            model_name="mention",
            old_name="url",
            new_name="wikipedia_url",
        ),
        migrations.RemoveField(
            model_name="mention",
            name="mention_text",
        ),
        migrations.AddField(
            model_name="mention",
            name="mention",
            field=models.CharField(default=None, max_length=500),
        ),
        migrations.AddField(
            model_name="mention",
            name="position",
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name="mention",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name="mention",
            name="blob_id",
            field=models.ForeignKey(
                db_column="blob_id",
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to="blobApp.blob",
            ),
        ),
    ]
