# Generated by Django 4.2.3 on 2023-07-25 16:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("blobApp", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Blob",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("url", models.URLField()),
                ("filename", models.CharField(max_length=255)),
                ("size", models.IntegerField()),
            ],
        ),
        migrations.AlterModelOptions(
            name="mention",
            options={"ordering": ("position",)},
        ),
        migrations.RemoveField(
            model_name="mention",
            name="mention_text",
        ),
        migrations.RemoveField(
            model_name="mention",
            name="url",
        ),
        migrations.AddField(
            model_name="mention",
            name="mention",
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AddField(
            model_name="mention",
            name="position",
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name="mention",
            name="wikipedia_url",
            field=models.URLField(default=None),
        ),
        migrations.AddField(
            model_name="mention",
            name="blob",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to="blobApp.blob",
            ),
        ),
    ]
