# Generated by Django 4.2.3 on 2023-07-28 15:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blobApp", "0002_blob_rename_url_mention_wikipedia_url_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blob",
            name="time",
            field=models.TimeField(default=datetime.time(15, 27, 26, 206096)),
        ),
    ]
