# Generated by Django 4.2.3 on 2023-07-27 15:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("blobApp", "0002_blob_alter_mention_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="mention",
            options={},
        ),
        migrations.RenameField(
            model_name="mention",
            old_name="blob",
            new_name="blob_id",
        ),
        migrations.RenameField(
            model_name="mention",
            old_name="position",
            new_name="rank",
        ),
        migrations.RemoveField(
            model_name="blob",
            name="filename",
        ),
        migrations.RemoveField(
            model_name="blob",
            name="size",
        ),
        migrations.RemoveField(
            model_name="blob",
            name="url",
        ),
        migrations.AddField(
            model_name="blob",
            name="blob",
            field=models.CharField(default=None, max_length=100, unique=True),
        ),
        migrations.AddField(
            model_name="blob",
            name="date",
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="mention",
            name="url",
            field=models.URLField(default=None),
        ),
        migrations.AlterField(
            model_name="blob",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="mention",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="mention",
            name="wikipedia_url",
            field=models.URLField(),
        ),
    ]
