# Generated by Django 4.2.3 on 2023-07-28 16:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blobApp", "0003_alter_blob_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blob",
            name="time",
            field=models.TimeField(default=datetime.time(16, 24, 34, 409808)),
        ),
    ]
