# Generated by Django 4.2.3 on 2023-07-28 19:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blobApp", "0004_alter_blob_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blob",
            name="time",
            field=models.TimeField(default=datetime.time(19, 9, 59, 472555)),
        ),
    ]
